name: C/C++ CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y make g++ clang-format
      
    - name: make
      run: make test
      
    - name: clang-format
      run: clang-format --dry-run --Werror src/*.cpp include/*.h
